config/routes.rb
Rails.application.routes.draw do

   root 'books#index'
   resources :books 

end

app/models/book.rb
class Book < ActiveRecord::Base
	has_attached_file :bookCover
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
	respond_to :html, :json
	
	def index
		respond_with(@books = Book.all)
	end

	def show
		respond_with(@book = Book.find(params[:id]))
	end

	def create
		@book = Book.new(book_params)
		debugger
		@book.save
		debugger
		respond_with @book
	end

	def update
		@book = Book.find(params[:id])
		@book.update_attributes(book_params)
		@book.save!
		respond_with @book
	end

	def destroy
		@book = Book.find(params[:id])
		@book.destroy
		respond_with @book
	end

	private

	def book_params
      params.require(:book).permit(:title, :author, :releaseDate,:bookCover, :coverImage, :keywords => []) 
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/index.html.erb
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8"/>
        <title>Backbone.js Library</title>
        
    </head>
    <body>
        <div id="books">
        <%= form_for :book, :url => books_path, :html => { :multipart => true } do |form| %>
            <%= form.file_field :bookCover %>
        <% end %>
        <form id="addBook" action="#" enctype="multipart/form-data">
            <div>
                <!-- <label for="coverImage">CoverImage: </label><input id="coverImage" type="file" /> -->
                <label for="title">Title: </label><input id="title" type="text" />
                <label for="author">Author: </label><input id="author" type="text" />
                <label for="releaseDate">Release date: </label><input type="text" id="releaseDate" >
                
                <label for="keywords">Keywords: </label><input id="keywords" type="text" />
                <button id="add">Add</button>
            </div>
        </form>
    </div>
    <script type="text/javascript">
    $(function () {
                $('#releaseDate').datepicker();
            });
</script>
    </body>
</html>

app/views/books/show.html.erb
<p>show</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Library</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>